language: python
dist: xenial
matrix:
  include:
    - python: "3.5"
addons:
    apt:
        packages:
            sox
            libsox-dev
            libsox-fmt-all
            libpython3.5-dev
install:
  - pip install torch
  - python setup.py install
script:
  - python -m unittest
